<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:center;font-size:12.0pt;font-family:"Times New Roman",serif;'>
    <img height="auto" src="http://abc_restaurant.webgenex.lk/assets/brand/abc_restaurantLogo.png" style="border:0;display:block;outline:none;text-decoration:none;width:100%;" width="64" />
</p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:center;font-size:12.0pt;font-family:"Times New Roman",serif;'><strong><u>Student Membership Registration &amp; Myabc_restaurant Credentials</u></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'><strong><u><span style="text-decoration:none;">&nbsp;</span></u></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'><strong>Full Name &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: <?php echo $full_name; ?></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'><strong>NIC No &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: &nbsp;<?php echo $nic; ?></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'><strong>abc_restaurant Student Registration No &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;: <?php echo $member_id; ?></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'><strong>Reg. Date &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: &nbsp;<?php echo $created_at; ?></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:justify;font-size:12.0pt;font-family:"Times New Roman",serif;'>We acknowledge with thanks the receipt of your application for membership registration. You have been registered as a student member of the Institute of Bankers of Sri Lanka with effect from the above date. Unless renewed by payment of &apos;Annual Subscription&apos; for each calendar year, your membership will be lapsed.</p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'>Your Credentials to log into Myabc_restaurant account are below:</p>
<ul style="list-style-type: disc;">
    <li>Username &nbsp; &nbsp; &nbsp; &nbsp;: <?php echo $email; ?></li>
    <li>Password &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;: <?php echo $password; ?></li>
    <li>Login Link &nbsp; &nbsp; &nbsp;: <a href="https://myabc_restaurant.abc_restaurant.lk/auth/user-login">https://myabc_restaurant.abc_restaurant.lk/auth/user-login</a></li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'><strong>Next:</strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'>Change your password (Recommended) by clicking on &quot;Reset password&quot; in the Customer Login portal after your first login.</p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'><strong>Now You Can log into&nbsp;</strong>Myabc_restaurant <strong>using the above Username &amp; Password&nbsp;</strong></p>
<ul style="list-style-type: disc;">
    <li>To explore new Courses.</li>
    <li>Apply for DBF Examination.</li>
</ul>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'>Your Student ID card along with the Student Registration confirmation letter will be sent to you via registered post in due course. <span style='font-family:"Cambria",serif;color:#222222;background:white;'>F</span><span style='font-size:15px;line-height:107%;font-family:"Cambria",serif;color:#222222;background:white;'>urther, we kindly request you to update any change of your mailing address or contact details &nbsp;via &nbsp;MYabc_restaurant Portal of &nbsp;the abc_restaurant &nbsp;website, &nbsp;</span><a href="http://www.abc_restaurant.lk/" target="_blank"><span style='font-size:15px;font-family:"Cambria",serif;color:blue;background:white;'>www.abc_restaurant.lk</span></a><span style='font-size:15px;line-height:107%;font-family:"Cambria",serif;color:#222222;background:white;'>&nbsp; to receive &nbsp;future correspondence on time.&nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'><span style='font-size:15px;line-height:107%;font-family:"Cambria",serif;color:#222222;background:white;'>Please verify the accuracy of your full name and the NIC number before applying for abc_restaurant examinations. &nbsp;</span></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:center;font-size:12.0pt;font-family:"Times New Roman",serif;'>&nbsp;</p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:center;font-size:12.0pt;font-family:"Times New Roman",serif;'><strong><em>For any clarifications related to Membership, please send an email to&nbsp;</em></strong><a href="mailto:mr@abc_restaurant.lk"><strong><em>mr@abc_restaurant.lk</em></strong></a><strong><em>, referring to your Student Registration number and the NIC number.&nbsp;</em></strong></p>
<p style='margin-top:0in;margin-right:0in;margin-bottom:8.0pt;margin-left:0in;text-align:left;font-size:12.0pt;font-family:"Times New Roman",serif;'>&nbsp;</p>
